#ifndef LIBOPERA_XBUS_CDROM_PLUGIN_H_INCLUDED
#define LIBOPERA_XBUS_CDROM_PLUGIN_H_INCLUDED

EXTERN_C_BEGIN

void* xbus_cdrom_plugin(int proc_, void* data_);

EXTERN_C_END

#endif /* LIBOPERA_XBUS_CDROM_PLUGIN_H_INCLUDED */
